### ISSUE TITLE
2.1.0 version : table.value.dt is not a function

### ISSUE THREAD

**Issue by mathieu-dumoutier** [DataTables/Vue#18]
Hi!

With version 2.1.0 when I follow this article : https://datatables.net/blog/2022-06-22-vue, I get a "table.value.dt is not a function" error when I try to use API.

It's work with 2.0.0

**Comment by AllanJard** [comment]
Try this one, which is using 2.1.0 of this component: https://stackblitz.com/edit/datatables-net-vue3-reactive-rx2tnv?file=src%2FApp.vue .

Note that it should just be:

```
onMounted(function () {
  dt = table.value.dt;
});
```

(i.e. don't execute the `dt` parameter).

If it isn't working in your application make sure you have the `ref="table"` attribute in your `<DataTable>` tag.

**Comment by mathieu-dumoutier** [comment]
Yes, it's work with dt and not dt() ! Thank you!

So this article https://datatables.net/blog/2022-06-22-vue is obsolete

**Comment by AllanJard** [comment]
Yes, that's wrong. I'll update it :)
